config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :books, only: %i(index show)
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :reviews, except: %i(new show)
    resources :stars, only: :index
    resources :users_relationships, only: %i(create destroy)

    namespace :admin do
      root "static_pages#index"
      resources :static_pages, only: :index
      resources :books, only: :index
    end
  end
end

app/views/admin/layouts/_admin_sidebar.html.erb
<div id="sidebar-wrapper" class="admin-sidebar-wrapper">
  <div class="sidebar-avatar">
    <%= image_tag get_avatar_url(current_user),
                  alt: t("avatar"), class: "avatar" %>
  </div>
  <ul class="sidebar-nav">
    <li><%= link_to t("home"), admin_root_path %></li>
    <li><%= link_to t("admin.manage_user"), "#" %></li>
    <li><%= link_to t("admin.manage_book"), admin_books_path %></li>
    <li><%= link_to t("admin.manage_genre"), "#" %></li>
    <li><%= link_to t("admin.user_interface"), root_path %></li>
    <li><%= link_to t("log_out"), logout_path, method: :delete %></li>
  </ul>
</div>

app/views/admin/layouts/application_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t "app_name" %></title>
  <%= render "layouts/shim" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application_admin", media: "all",
                          "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application_admin",
                          "data-turbolinks-track": "reload" %>
</head>
<body>
<div id="wrapper">
  <%= render "admin/layouts/admin_sidebar" %>
  <div id="page-content-wrapper" class="admin-page-content-wrapper">
    <div id="page-container">
      <div id="container">
        <h1 id="name-app-header"><%= t "admin_interface" %></h1>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
        <% end %>
        <ul class="page-header">
          <li><h2 class="page-title"><%= yield :page_title %></h2></li>
          <%= render "shared/language" %>
        </ul>
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>