config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :books, only: %i(index show)
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :reviews, except: %i(new show)
    resources :stars, only: :index
    resources :users_relationships, only: %i(create destroy)

    namespace :admin do
      root "static_pages#index"
      resources :static_pages, only: :index
      resources :books, only: :index
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, except: :index
  before_action :find_review_by_id, only: %i(edit update destroy)
  before_action :check_update_permission, only: %i(edit update)
  before_action :check_delete_permission, only: :destroy

  def index
    book_id = params[:book_id]
    @reviews = Review.by_book_id(book_id).by_rating(params[:rating])
                     .order_by_time_created
    respond_to do |format|
      format.html{redirect_to book_path book_id}
      format.js
    end
  end

  def create
    create_params = review_params
    create_params[:user_id] = current_user.id
    @review = Review.new create_params
    if @review.save
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to book_path create_params[:book_id]
  end

  def edit
    respond_to do |format|
      format.html{redirect_to book_path @review.book_id}
      format.js
    end
  end

  def update
    if @review.update review_params
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to book_path @review.book_id
  end

  def destroy
    if @review.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to book_path @review.book_id
  end

  private

  def review_params
    params.require(:review).permit(Review::CREATEABLE_ATTRS)
  end

  def check_delete_permission
    return @review if can_delete_review? @review

    flash[:danger] = t ".not_allow_delete"
    redirect_to book_path @review.book_id
  end

  def check_update_permission
    return @review if can_update_review? @review

    flash[:danger] = t ".not_allow_update"
    redirect_to book_path @review.book_id
  end

  def find_review_by_id
    @review = Review.find_by id: params[:id]
    return if @review

    flash[:warning] = t ".review_not_found"
    redirect_to root_path
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def make_statistic rating, reviews
    number_of_review = reviews.by_rating(rating).count
    html = "<div class=\"statistic\">"
    html << "( <span class=\"bold green\">#{number_of_review}</span> ) "
    html << "<i class=\"fa-solid fa-star\"></i> " * rating
    html << "<i class=\"fa-regular fa-star\">
      </i> " * (Settings.book.MAX_RATING - rating)
    html << "<input type=\"hidden\" name=\"rating\" id=\"rating\"
      value=\"#{rating}\">"
    html << "</div>"
    html
  end

  def make_star_rating rating
    html = ""
    Settings.book.MAX_RATING.times do |n|
      html << if n + 1 <= rating.to_i
                "<div class=\"rating-star\" data-value=#{n + 1}>
          <i class=\"fa-solid fa-star\"></i> </div>"
              else
                "<div class=\"rating-star\" data-value=#{n + 1}>
          <i class=\"fa-regular fa-star\"></i> </div>"
              end
    end
    html
  end

  def get_time_create review
    review.created_at.in_time_zone(Settings.time_zone)
          .strftime("%H:%M %Y-%m-%d")
  end
end

app/views/reviews/_review.html.erb
<div class="review-card" id="review-card-<%= review.id %>">
  <% user = find_user_by_id review.user_id %>
  <div class="image">
    <%= image_tag get_avatar_url(user), alt: t("avatar"), class: "avatar" %>
  </div>
  <div class="infor">
    <div class="user-name bold nunito">
      <% if show_book_title %>
        <% book = find_book_by_input_id review.book_id %>
        <%= link_to user.name, user_path(user), class: "green" %>
        <span><%= t "reviewed_for" %></span>
        <%= link_to book.title, book_path(book), class: "green" %>
      <% else %>
        <%= link_to user.name, user_path(user), class: "green" %>
      <% end %>
    </div>
    <div class="form">
      <div class="rating">
        <% Settings.book.MAX_RATING.times do |n| %>
          <% if n + 1 <= review.rating %>
            <i class="fa-solid fa-star"></i>
          <% else %>
            <i class="fa-regular fa-star"></i>
          <% end %>
        <% end %>
      </div>
      <div class="review-content nunito">
        <p><%= review.content %></p>
      </div>
      <div class="create-at nunito">
        <span><%= get_time_create review %></span>
      </div>
      <% if logged_in? %>
        <div class="review-action bold">
          <% if can_update_review? review %>
            <%= link_to t("update"), edit_review_path(review), remote: true %>
          <% end %>
          <% if can_delete_review? review %>
            <%= link_to t("delete"), review_path(review), method: :delete %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_review_form.html.erb
<%= form_for @review do |f| %>
  <div class="field" id="rating-star-container">
    <%= make_star_rating(@review.rating || 0).html_safe %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: t("reviews.compose_new_review"),
                    class: "nunito" %>
  </div>
  <%= f.hidden_field :rating %>
  <%= hidden_field_tag :create_review_action, stars_path %>
  <%= f.hidden_field :book_id, value: @book.id if @book %>
  <%= f.submit button_text, class: "btn btn-primary my-button" %>
<% end %>

app/views/reviews/_reviews.html.erb
<%= render partial: "reviews/review", collection: reviews,
           locals: {show_book_title: show_book_title} %>

app/views/reviews/_statistic_review.html.erb
<div id="statistic-review">
  <%= make_statistic(5, @reviews_of_book).html_safe %>
  <%= make_statistic(4, @reviews_of_book).html_safe %>
  <%= make_statistic(3, @reviews_of_book).html_safe %>
  <%= make_statistic(2, @reviews_of_book).html_safe %>
  <%= make_statistic(1, @reviews_of_book).html_safe %>
  <%= hidden_field_tag :action, reviews_path %>
  <%= hidden_field_tag :book_id, @book.id %>
</div>

app/views/reviews/edit.js.erb
$('#review-card-<%= @review.id %> .form').html('<%= j render partial: "reviews/review_form", locals: {button_text: t("save")} %>')

app/views/reviews/index.js.erb
$('#reviews_list').html('<%= j render partial: "reviews/reviews", locals: {reviews: @reviews, show_book_title: false} %>');