config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :books, only: %i(index show)
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :reviews, except: %i(new show)
    resources :stars, only: :index
    resources :users_relationships, only: %i(create destroy)

    namespace :admin do
      root "static_pages#index"
      resources :static_pages, only: :index
      resources :books, only: :index
    end
  end
end

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all",
                        "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div id="sidebar-wrapper">
  <div class="sidebar-avatar">
    <% if logged_in? && current_user.picture %>
      <%= image_tag current_user.picture_url, alt: t("avatar"), class: "avatar" %>
    <% else %>
      <%= image_tag "avatar_example.png", alt: t("avatar"), class: "avatar" %>
    <% end %>
  </div>
  <ul class="sidebar-nav">
    <li><%= link_to t("home"), root_path %></li>
    <li><%= link_to t("book"), books_path %></li>
    <% if logged_in? %>
      <li><%= link_to t("profile"), user_path(current_user) %></li>
      <% if current_user.admin? %>
        <li><%= link_to t("admin_interface"), admin_root_path %></li>
      <% end %>
      <li><%= link_to t("log_out"), logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to t("sign_in"), login_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "app_name" %></title>
    <%= render "layouts/shim" %>
    <%= render "layouts/rails_default" %>
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/sidebar" %>
      <div id="page-content-wrapper">
        <div class="btn" id="menu-toggle">
          <i class="fa-solid fa-bars"></i>
        </div>
        <div id="page-container">
          <div id="container">
            <h1 id="name-app-header"><%= t "app_name" %></h1>
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>">
                <%= message %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>